source_bios_dir: "/mnt/storage/Games/BIOS Files"
source_roms_dir: "/mnt/storage/Games/ROMs/Curated"
source_batocera_scraped_media_dir: "/mnt/storage/Games/Artwork/Batocera/roms/"
source_esde_scraped_media_dir: "/mnt/storage/Games/Artwork/ES-DE/downloaded_media"
remote_hostname: "nas-01"

bios_subdirs:
  arcade_finalburnneo: "Arcade - Final Burn Neo"
  arcade_mame2003plus: "Arcade - MAME 2003 Plus"
  nec_turbografx_16: "NEC - PC Engine - TurboGrafx 16"
  nec_turbografx_cd: "NEC - PC Engine CD - TurboGrafx-CD"
  nintendo_3ds: "Nintendo - 3DS"
  nintendo_ds: "Nintendo - DS"
  nintendo_game_boy_advance: "Nintendo - Game Boy Advance"
  nintendo_game_boy_color: "Nintendo - Game Boy Color"
  nintendo_game_boy: "Nintendo - Game Boy"
  nintendo_gamecube: "Nintendo - GameCube"
  nintendo_super_game_boy: "Nintendo - Super Game Boy"
  pico_8: "Lexaloffle - PICO-8"
  sega_cd: "Sega - Sega CD"
  sega_dreamcast: "Sega - Dreamcast"
  sega_saturn: "Sega - Saturn"
  snk_neo_geo: "SNK - Neo Geo"
  snk_neo_geo_cd: "SNK - Neo Geo CD"
  sony_playstation: "Sony - Playstation"
  sony_playstation_2: "Sony - Playstation 2"
  sony_playstation_vita: "Sony - Playstation Vita"

roms_subdirs:
  arcade_finalburnneo: "Arcade - Final Burn Neo (1.0.0.3 Best Set)"
  arcade_mame2003plus: "Arcade - MAME 2003 Plus (Tiny Best Set)"
  atari_2600: "Atari - 2600"
  atari_5200: "Atari - 5200"
  atari_7800: "Atari - 7800"
  atari_jaguar: "Atari - Jaguar"
  atari_lynx: "Atari - Lynx"
  cbs_colecovision: "CBS - Colecovision"
  commodore_64: "Commodore - 64"
  nec_turbografx_16: "NEC - TurboGrafx 16"
  nec_turbografx_cd: "NEC - TurboGrafx-CD (Tiny Best Set)"
  nintendo_64: "Nintendo - Nintendo 64"
  nintendo_ds: "Nintendo - Nintendo DS (Retro ROMs Best Set)"
  nintendo_famicom_disk_system: "Nintendo - Famicom Disk System"
  nintendo_game_boy_advance: "Nintendo - Game Boy Advance"
  nintendo_game_boy_color: "Nintendo - Game Boy Color"
  nintendo_game_boy: "Nintendo - Game Boy"
  nintendo_gamecube: "Nintendo - GameCube (Retro ROMs Best Set)"
  nintendo_nes: "Nintendo - Nintendo Entertainment System"
  nintendo_snes: "Nintendo - Super Nintendo Entertainment System"
  nintendo_super_game_boy: "Nintendo - Super Game Boy"
  nintendo_switch: "Nintendo - Nintendo Switch"
  nintendo_wii: "Nintendo - Wii (Minimal)"
  nintendo_wiiu: "Nintendo - WiiU (Minimal)"
  pico_8: "Lexaloffle - PICO-8"
  sega_32x: "Sega - Sega 32X"
  sega_cd: "Sega - Sega CD (Tiny Best Set)"
  sega_dreamcast: "Sega - Dreamcast (Retro ROMs Best Set)"
  sega_game_gear: "Sega - Game Gear"
  sega_genesis: "Sega - Genesis"
  sega_master_system: "Sega - Master System"
  sega_saturn: "Sega - Saturn (Retro ROMs Best Set)"
  sega_sg_1000: "Sega - SG-1000"
  snk_neo_geo: "SNK - Neo Geo"
  snk_neo_geo_cd: "SNK - Neo Geo CD"
  snk_neo_geo_pocket: "SNK - Neo Geo Pocket"
  snk_neo_geo_pocket_color: "SNK - Neo Geo Pocket Color"
  sony_playstation: "Sony - Playstation (Tiny Best Set)"
  sony_playstation_2: "Sony - Playstation 2 (Top 100)"
  sony_playstation_portable: "Sony - Playstation Portable (Retro ROMs Best Set)"
